Remove invalid option.
`opendistro_security.audit.enable_request_details` is not valid anymore.

I tried with ODFE 1.6.0 and ES gives the following error:

```
[2020-04-10T16:52:22,592][ERROR][o.e.b.Bootstrap          ] [data01] Exception
java.lang.IllegalArgumentException: unknown setting [opendistro_security.audit.enable_request_details] did you mean any of [opendistro_security.audit.enable_rest, opendistro_security.audit.enable_transport, opendistro_security.audit.log_request_body]?
```

(cherry picked from commit 823693f19e0a9d78806d8a4fd96c3b41dbd3e770)